language: python
sudo: required
cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - docker

before_install:
  - docker-compose up -d

install:
  - pip install -r requirements-dev.txt

script:
  - pytest -sv tests.py
  
